language: python
python:
  - "3.9.1"
services:
  - xvfb
addons:
  apt:
    packages:
      - firefox-geckodriver
      - ffmpeg
install:
  - "pip install pipenv pytest"
  - "pipenv install"
script: python -m pytest tests/