language: python
python:
  - "3.9.1"
addons:
  homebrew:
    casks:
      - firefox
    packages:
      - imagemagick
      - geckodriver
install:
  - "pip install pipenv pytest"
  - "pipenv install"
script: python -m pytest tests/